### ISSUE TITLE
how to set CacheBust number as a static

### ISSUE THREAD

**Issue by sundarkota** [getify/LABjs#100]
Hi,

Every release of production we are getting cache issue, user didn't remove browser cache, to avoid this issue i need to set a query string as static. instead of adding every time file loaded(dynamic variable which is exist now).

Suppose last month release version is 20140909, so query string is need to be add as ?_20140909.
And this month we have release and need to be add query string as ?_20141020.

This feature is not available please implement as like in setoption(global variable).

Every release of product, we are asking our customer to force the cache clear. after implementation of this feature we no need to bother about cache issue every product release.

Many thanks in advance

**Comment by getify** [comment]
LABjs only supports generating random numbers to append to the end of the query string (for cache busting). If you're implementing logic that gives meaning to the values in your URLs, you need to manage that in a layer that produces the URLs you feed to LABjs.
