### ISSUE TITLE
Possible to exclude specific scripts?

### ISSUE THREAD

**Issue by JordanMagnuson** [getify/LABjs#102]
Is it possible to exclude specific scripts from being processed by LabJS? 

For example, when using <a href="https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-">Cloudflare's Rocket Loader</a> (which similarly loads all js on a page asynchronously), it is possible to exclude a specific script by addingd "data-cfasync='false'" to the script tag, like so: 

`<script data-cfasync='false' src=...>`

The script is then left alone by Rocket Loader, and loaded in the usual way... is it possible to accomplish something similar with LabJS?

**Comment by getify** [comment]
LABjs doesn't load anything that you don't explicitly pass to a `script(..)` call on the API. So I'm confused as to what need LABjs would need to ignore? Just don't pass it something you don't want it to load.

**Comment by JordanMagnuson** [comment]
Sorry, getify, I'm using the [Drupal LabJS module](https://www.drupal.org/project/labjs), which grabs all the js on the page... I thought the issue was with LabJS itself, but I see it's the module that's responsible for this behavior. Apologies for my hasty post.

**Comment by getify** [comment]
Cheers! :)
