### ISSUE TITLE
Can't load files containing 'nestable' in their name

### ISSUE THREAD

**Issue by PXLRic** [getify/LABjs#104]
Trying to load jquery.nestable.js will fail. Renaming and excluding 'nestable' from the filename works:

jquery.nestable.js - fails
nestable.js - fails
jquery-nestable.js - works

**Comment by getify** [comment]
LABjs doesn't have any code in it that even includes the word "nestable", so it's definitely not filtering out those files. Your issue must be related to something else, either software on your computer or something in your server configuration, or something like that.

**Comment by getify** [comment]
Closing for now. Reopen if there's more specific evidence to share.
