### ISSUE TITLE
LABjs reads from cache when f5

### ISSUE THREAD

**Issue by hanzichi** [getify/LABjs#107]
my code is quite easy that  contains only one line “$LAB.script('index.js')”
I use my wampserver to have a test, when I press f5, i intend to load data from the server, but the fact is as below
![20150730164443](https://cloud.githubusercontent.com/assets/10890665/8979260/f55c7130-36da-11e5-95d1-2e070ce7d048.png)

it seems it reads data from the cache, when I change the code, it does not present the right data. but I have pressed f5, I do not know how to get what I really want, or it is a problem of wampserver? or labjs? please help me, with full thanks.

**Comment by getify** [comment]
duplicate
