### ISSUE TITLE
Config CDN failure fallback

### ISSUE THREAD

**Issue by albertvp** [getify/LABjs#109]
Hi, we are currently using AngularJS with browserify.
Our goal is to load the framework and libraries asynchronously before our app.
We are considering to use LABjs on production (instead of lazy requirejs / browserify-shim / require-jquery) because is a minimal and smart way to do it.
My question is if we want to set fallback for an unavailable CDN source we have to code it with a wait callback checking if is loaded or do we have a failure one?
Thanks for the contribution!

**Comment by albertvp** [comment]
Ok I see your comment there https://github.com/getify/LABjs/pull/85#issuecomment-20476024 and your solution gist https://gist.github.com/getify/670840

**Comment by getify** [comment]
That's what I was going to point you to. :) Cheers.
