### ISSUE TITLE
BOM issues

### ISSUE THREAD

**Issue by jdalton** [getify/LABjs#110]
I've had a few Windows Web App folks report issues trying to load scripts with LABjs if they contain a trailing BOM. I'm wondering if there's a known workaround for this or an idea of where things could be going wrong?

**Comment by getify** [comment]
uhhh... i have no idea what that would be. since LABjs just does loading via normal `<script>` tags in all modern browsers, I would think this would be an issue that was replicatable outside of LABjs' code. Any chance we could get an affected file to test with?

**Comment by jdalton** [comment]
I'll try to get something together.

**Comment by getify** [comment]
Closing for now. Feel free to add more details if this crops up again and seems to be LABjs related.

**Comment by jdalton** [comment]
:sunglasses:
