### ISSUE TITLE
HTTP2 or SPDY and LABjs

### ISSUE THREAD

**Issue by ralfbecker** [getify/LABjs#111]
We (www.egroupware.org) use LABjs to load all our client-side scripts, which currently get minified and concatenated on server-side.
With arrival of SPDY and HTTP2, concatenation seems no longer be necessary, not to say even harmful performance-wise. 
So I wonder if LABjs would load 100+ scripts in parallel or it only loads N at one time? HTTP2 (and SPDY) handle that over a single tcp connection.
If LABjs itself limits the number of scripts loaded at one time, it would make sense to detect HTTP2/SPDY and switch off that limitation, or is the limitation done by browser itself and therefore no need to change anything in that regard in LABjs for HTTP2 or SPDY.

**Comment by getify** [comment]
LABjs places no limits (or controls) over how parallel a browser will load requested resources. So there's nothing to change in LABjs for that.

It remains an unknown to me how to tell the browser (if anything) that you want requests to be interleaved on a single connection. I believe that may happen automatically, but I suppose it's possible it may need a client-side change. I've not heard any details about that. It's also possible that it requires no extra work on the client, but may require changes to the server to recognize these requests and combine the responses into one connection. Again, I have not investigated any of these specific details.

If there ends up being something specific LABjs would need to change to adopt HTTP2 conventions for parallelism of connections, I'm happy to entertain discussion.

**Comment by ralfbecker** [comment]
Thanks for the quick response :-)
I expected so much, as I could not find anything in your code.
I believe, if LABjs is not restricting the number of parallel loads, browsers supporting HTTP2 or SPDY which is basically everything, but IE < 11, will do the rest automatic, when talking to a HTTP2/SPDY supporting server.
