### ISSUE TITLE
swallowing errors doesn't seem right

### ISSUE THREAD

**Issue by cherouvim** [getify/LABjs#112]
$LAB.script('foo.js').wait(function() {
        console.log('shown');
        whatever;
        // code that will never execute but we don't know that
    });

This code should thrown an error because "whatever" is not defined. Instead it shows nothing in the console and the programmer thinks that "// code that will never execute... " does execute.

I've seen that the debug version of LAB shows the error, but why hide these errors in the first place? It doesn't seem right.

**Comment by getify** [comment]
Please see: https://github.com/getify/LABjs/issues/19#issuecomment-50981147 (and other closed issue threads)
