### ISSUE TITLE
LAB inserts scripts at the beginning of the <head>

### ISSUE THREAD

**Issue by xaddict** [getify/LABjs#115]
LABjs insert scripts at the beginning of the <head> instead of at the end of the <head> or even the end of the <body> tag. Is there a reason for this and could it be changed in upcoming versions?

**Comment by devilking15292** [comment]
if you want to add the downloaded scripts to the end of the head tag .. just open LAB.src.js
and replace this line 

`append_to.insertBefore(script,append_to.firstChild);`
 with 
 ` append_to.appendChild(script);` 

in line numbers  174, 183, 190 and 244. 

 hope it satisfies your need .. 

**Note**:  this is a non tested solution .

**Comment by getify** [comment]
@xaddict why does it matter where LABjs adds the scripts?

**Comment by xaddict** [comment]
Well, for one, Audits by Google wants scripts in a certain place and having
to ignore a bunch of rules just because LABjs does it that way can be
annoying if you have loads of projects all running through audits and
pagespeed. Plus, it's common esthetic practice to not put them before the
title or base tags

**Comment by getify** [comment]
Those audits or whatever they are, are being rather naive if they're penalizing you for dynamically added scripts in the `<head>`. It's true it's not a great idea for that in the orig source code, but this is all dynamic, so its placement won't have any difference or impact at all.

Not sure this kind of feature would be useful to a broad enough audience to make it worth the bytes. But perhaps.

**Comment by getify** [comment]
LABjs is going to append resource requests to the end of the `<head>` from 3.0 onward.

**Comment by tonyporto** [comment]
Thank you for all the work you put into this, I actively use labjs & great to see that your back to actively making it better then what it already is...

**Comment by xaddict** [comment]
Awesome!

I hate to be a stick-in-the-mud but could it be an option to add resources to:

1. the end of the `<head>`
2. the end of the `<body>`

I know LABjs is async and deferred by design (defer the loading of LABjs and the script that calls LABjs) but PageSpeed Insights, WooRank, Feed the Bot, and other SEO tools are real bitches about order and placement of inserted scripts. For example, scripts that are before stylesheets or in order one after another (script, stylesheet, script, stylesheet) negatively impact the reports from these tools. It's very annoying but could be stopped by injecting scripts at the end of the `<body>` and stylesheets at the end of the `<head>`.
