### ISSUE TITLE
how to use LAB when Chrome blocks inline scripts ?

### ISSUE THREAD

**Issue by razorree** [getify/LABjs#117]
I can't use LAB like this:

```
<script>
   $LAB
   .script("framework.js").wait()
   .script("plugin.framework.js")
   .script("myplugin.framework.js").wait()
   .script("init.js").wait();
</script>
```

because Chrome blocks inline scripts.
If i put that code in separate js file, quite often $LAB is undefined....

**Comment by jbmonroe** [comment]
Erm...what?  Are you saying that if you open Chrome with the following

<!DOCTYPE html>
<html>
<head>
    <title>Chrome Not Blocking an Inline Script</title>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <style>
        body { font-family : Arial }
    </style>
</head>
<body>
    <script>
        const div = document.createElement("div");
        div.textContent = `Hi, I'm ${navigator.userAgent} and I'm not blocking this inline script`;
        document.body.appendChild(div);
    </script>
</body>
</html>

you get a blank page?

**Comment by getify** [comment]
Chrome does not block inline scripts, unless the server it's served from is sending CSP policy to prevent it -- in which case there's nothing we can do to fix that.
