### ISSUE TITLE
labjs.com is down

### ISSUE THREAD

**Issue by dschnare** [getify/LABjs#123]
Hey Kyle,

The project's home page labjs.com has been down for quite some time. Can you have a look at that?

The only reason I bring it up is because that's where most of the documentation lives.

-Darren

**Comment by getify** [comment]
My servers have been down since last July. I haven't had time to rebuild them. The data wasn't lost, but I don't have anything to put up right now.

In the interim, the whole site should be available for review (docs wise) here: http://web.archive.org/web/20160521005010/http://labjs.com/
