### ISSUE TITLE
Recovering from 404

### ISSUE THREAD

**Issue by dschnare** [getify/LABjs#124]
Hey,

Is there any way to recover from a script not found/404 error in the `wait()` callback?
For example:
```
$LAB.script('/scripts/my-script.min.js').wait(function (statusCode) {
  if (statusCode === 404) {
    $LAB.script('/scripts/my-script.js')
  }
})
```
Or an even better API would be:
```
$LAB.script('/scripts/my-script.min.js').fallback('/scripts/my-script.js')
```

**Comment by getify** [comment]
Error handling on resource requests is notoriously inconsistent (differences between 4xx and 5xx HTTP error codes, for example). As such, I don't want to try to bake reliance on that inconsistent behavior into LABjs.

However, in 3.0, LABjs is going to support an error notification (of some sort), so you can at least be notified if any error events are fired against the resource elements. That probably won't help much in recovery, but at least you could log the failure.
