### ISSUE TITLE
Refactor out arguments.callee

### ISSUE THREAD

**Issue by dschnare** [getify/LABjs#125]
Refactor out the usage of `arguments.callee` on this [line](https://github.com/getify/LABjs/blob/master/LAB.src.js#L123)

That makes me uneasy. Is that supported by the latest browsers still? Hasn't it been deprecated a long time ago?

**Comment by getify** [comment]
It's illegal as of strict mode. It should be refactored. Easy fix is to name the function expression (passed to the setTimeout) and use that function name.

NOTE: the library is undergoing a complete rewrite for 3.0, so there's no need to PR to fix this, because it'll be fixed in that rewrite.
