### ISSUE TITLE
[Question] Does LABjs scrub out the debugger keyword?

### ISSUE THREAD

**Issue by openly-retro** [getify/LABjs#133]
Hi -- I am attempting to troubleshoot some code that is queued into LABjs via an anonymous function. I have inserted a few debugger statements but they don't seem to trigger. As part of my troubleshooting, could you confirm that LABjs doesn't scrub out debugger statements?

**Comment by getify** [comment]
It does not touch the loaded code in any way.

**Comment by openly-retro** [comment]
Thank you very much for confirming!
