### ISSUE TITLE
Javascript Redirect  window.location.href   Not Working 

### ISSUE THREAD

**Issue by cuizeng247** [getify/LABjs#86]
I'd like to make an auto redirect if some condition is true. 
After chain loading several js files, the following   " window.location.href  " in one of the end chain file does not work.

example code:

``` js
if (true;) { 
        $LAB
        .script("dataObject.js")
        .wait(function(){
                  // if " window.location.href " was here, it worked! 
            for (var i in dataObject) {
                    var example = i.match("a");
                    if (example != null){
                        alert("ok here!");   // reached here
                        window.location.href = 'http://www.example.com';
                        alert("not reached here...");  // not reached here
                        break;
                    } 
            }
        });
}
```

Also I am told that /< a href="javascript:void(0)" >/ is built into window.location.href. (not sure if it relates to the problem)

I am a javascript idiot, so could anyone give out workable code please? 
Thank you very much!

**Comment by vajrayanu** [comment]
@getify  how to send parameter to controller by 'window.location.href'

**Comment by lordspace** [comment]
@CreativForm hey, thank's for sharing your solution for the redirect. 
I think the equal signs should be ==, otherwise you're assigning a value and not comparing.

**Comment by InfinitumForm** [comment]
> @CreativForm hey, thank's for sharing your solution for the redirect.
> I think the equal signs should be ==, otherwise you're assigning a value and not comparing.

No, there I not comparing. I trying to do redirection and if fail it will return `NULL` and go to `else`. If  redirection is successful, there is no `NULL` and we finish this code.

**Comment by lordspace** [comment]
> > @CreativForm hey, thank's for sharing your solution for the redirect.
> > I think the equal signs should be ==, otherwise you're assigning a value and not comparing.
> 
> No, there I not comparing. I trying to do redirection and if fail it will return `NULL` and go to `else`. If redirection is successful, there is no `NULL` and we finish this code.

interesting. didn't think of that case

**Comment by berkaykosak** [comment]
function GoToApp(e) {
            document.location = site_url+ "://";
            setTimeout(function () {
                window.location = $(e).data("store_link");
            }, 3000);
        }
